/* Generated By:JavaCC: Do not edit this line. AssConstants.java */
package org.catacombae.xml.parser;

public interface AssConstants {

  int EOF = 0;
  int S = 1;
  int CHAR = 2;
  int NAME = 3;
  int NAMECHAR = 4;
  int LETTER = 5;
  int BASECHAR = 6;
  int IDEOGRAPHIC = 7;
  int COMBININGCHAR = 8;
  int DIGIT = 9;
  int EXTENDER = 10;
  int REFERENCE = 11;
  int ENTITYREF = 12;
  int CHARREF = 13;
  int STARTTAG = 14;
  int STARTCLOSINGTAG = 15;
  int STARTPI = 16;
  int STARTXMLDECL = 17;
  int STARTDOCTYPEDECL = 18;
  int STARTCOMMENT = 19;
  int STARTCDATA = 20;
  int DEFAULT_S = 21;
  int CHARDATA = 22;
  int DEFAULT_REFERENCE = 23;
  int ENDXMLDECL = 24;
  int XMLDECL_S = 25;
  int XMLDECL_EQ = 26;
  int XD_DQUOTE_OPEN = 27;
  int XD_SQUOTE_OPEN = 28;
  int VERSION = 29;
  int ENCODING = 30;
  int STANDALONE = 31;
  int XD_DQUOTE_STRING = 32;
  int XD_DQUOTE_CLOSE = 33;
  int XD_SQUOTE_STRING = 34;
  int XD_SQUOTE_CLOSE = 35;
  int VERSION_DOPEN = 36;
  int VERSION_DCLOSE = 37;
  int VERSION_SOPEN = 38;
  int VERSION_SCLOSE = 39;
  int VER = 40;
  int STANDALONE_DOPEN = 41;
  int STANDALONE_DCLOSE = 42;
  int STANDALONE_SOPEN = 43;
  int STANDALONE_SCLOSE = 44;
  int STANDALONE_YES = 45;
  int STANDALONE_NO = 46;
  int WDD_S = 47;
  int WDD_NAME = 48;
  int ENDDOCTYPEDECL = 49;
  int EXTERNALID = 50;
  int SYSTEMLITERAL = 51;
  int PUBIDLITERAL = 52;
  int PUBIDCHAR = 53;
  int BEGIN_INTSUBSET = 54;
  int END_INTSUBSET = 55;
  int WHATEVER = 56;
  int ENDCOMMENT = 57;
  int COMMENT_ILLEGAL = 58;
  int COMMENT_CHAR = 59;
  int ENDPI = 60;
  int ILLEGALTARGET = 61;
  int PITARGET = 62;
  int WITHINPI_S = 63;
  int PC_CHAR = 64;
  int WT_NAME = 65;
  int WT_EQ = 66;
  int WT_S = 67;
  int WT_DQUOTE = 68;
  int WT_SQUOTE = 69;
  int EMPTY_ENDTAG = 70;
  int ENDTAG = 71;
  int ATTR_DQUOTE = 72;
  int ATTR_SQUOTE = 73;
  int ATTR_DQUOTE_STRING = 74;
  int ATTR_SQUOTE_STRING = 75;
  int ATTR_REFERENCE = 76;
  int ENDCDATA = 77;
  int WCD_CHAR = 78;

  int WithinCData = 0;
  int Attribute = 1;
  int WithinTag = 2;
  int WithinPIContent = 3;
  int WithinPI = 4;
  int Comment = 5;
  int WithinIntSubset = 6;
  int WithinDoctypeDecl = 7;
  int WithinXMLDecl_Standalone = 8;
  int WithinXMLDecl_Version = 9;
  int WithinXMLDecl_SquoteString = 10;
  int WithinXMLDecl_DquoteString = 11;
  int WithinXMLDecl = 12;
  int DEFAULT = 13;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "<CHAR>",
    "<NAME>",
    "<NAMECHAR>",
    "<LETTER>",
    "<BASECHAR>",
    "<IDEOGRAPHIC>",
    "<COMBININGCHAR>",
    "<DIGIT>",
    "<EXTENDER>",
    "<REFERENCE>",
    "<ENTITYREF>",
    "<CHARREF>",
    "\"<\"",
    "\"</\"",
    "\"<?\"",
    "\"<?xml\"",
    "\"<!DOCTYPE\"",
    "\"<!--\"",
    "\"<![CDATA[\"",
    "<DEFAULT_S>",
    "<CHARDATA>",
    "<DEFAULT_REFERENCE>",
    "\"?>\"",
    "<XMLDECL_S>",
    "\"=\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"version\"",
    "\"encoding\"",
    "\"standalone\"",
    "<XD_DQUOTE_STRING>",
    "\"\\\"\"",
    "<XD_SQUOTE_STRING>",
    "\"\\\'\"",
    "\"=\\\"\"",
    "\"\\\"\"",
    "\"=\\\'\"",
    "\"\\\'\"",
    "\"1.0\"",
    "\"=\\\"\"",
    "\"\\\"\"",
    "\"=\\\'\"",
    "\"\\\'\"",
    "\"yes\"",
    "\"no\"",
    "<WDD_S>",
    "<WDD_NAME>",
    "\">\"",
    "<EXTERNALID>",
    "<SYSTEMLITERAL>",
    "<PUBIDLITERAL>",
    "<PUBIDCHAR>",
    "\"[\"",
    "\"]\"",
    "<WHATEVER>",
    "\"-->\"",
    "\"--\"",
    "<COMMENT_CHAR>",
    "\"?>\"",
    "<ILLEGALTARGET>",
    "<PITARGET>",
    "<WITHINPI_S>",
    "<PC_CHAR>",
    "<WT_NAME>",
    "\"=\"",
    "<WT_S>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"/>\"",
    "\">\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "<ATTR_DQUOTE_STRING>",
    "<ATTR_SQUOTE_STRING>",
    "<ATTR_REFERENCE>",
    "\"]]>\"",
    "<WCD_CHAR>",
  };

}
